name: Run Selenium Cucumber Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout project
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 📦 Build project
        run: mvn clean install -DskipTests

      - name: 🌐 Run tests
        run: mvn test

      - name: 📊 Upload Cucumber Report
        uses: actions/upload-artifact@v4
        with:
          name: Cucumber-Report
          path: target/
